### ISSUE TITLE
ISDA SIMM errors

### ISSUE THREAD

**Issue by ricardordiz** [meenmo/ISDA_SIMM#8]
I face the following errors:

C:\Users\dizri\Desktop\ISDA_SIMM-main\src>python main.py
Traceback (most recent call last):
  File "C:\Users\dizri\Desktop\ISDA_SIMM-main\src\main.py", line 2, in <module>
    import agg_margins
  File "C:\Users\dizri\Desktop\ISDA_SIMM-main\src\agg_margins.py", line 7, in <module>
    from   margin_risk_class import MarginByRiskClass
  File "C:\Users\dizri\Desktop\ISDA_SIMM-main\src\margin_risk_class.py", line 3, in <module>
    from   scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'

Could you please help me?

**Comment by meenmo** [comment]
You should install scipy.

Try this: pip install scipy
